<a href="https://colab.research.google.com/github/thonyvel98/InteligenciaArtificial2024-2/blob/main/Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
matrixA = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(matrixA.shape)

(3, 4)


In [4]:
matrixA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
print(matrixA[1:,1:3])

[[ 6  7]
 [10 11]]


In [59]:
matrixB = np.random.randint(0, 10, size=(4, 3))
print(matrixB)

[[1 0 6]
 [9 2 8]
 [5 5 6]
 [3 9 2]]


In [53]:
print(matrixB)
col_indices = np.array([0, 2, 1])
row_indices = np.array([1, 2])

for row, col in zip(row_indices, col_indices):
    #print(row, "-" , col)
    print(matrixB[row, col])

[[2 2 2]
 [8 2 0]
 [0 1 8]
 [1 4 8]]
8
8


In [54]:
filtro=matrixB>7
print(filtro)

[[False False False]
 [ True False False]
 [False False  True]
 [False False  True]]


In [55]:
print(matrixB[filtro])

[8 8 8]


In [58]:
print(matrixB[matrixB>7])

[102 102 102 108 102 100 100 108 104 108]


In [57]:
print(matrixB)

matrixB[matrixB % 2 == 0] += 100
matrixB

[[2 2 2]
 [8 2 0]
 [0 1 8]
 [1 4 8]]


array([[102, 102, 102],
       [108, 102, 100],
       [100,   1, 108],
       [  1, 104, 108]])

In [50]:
print(matrixB)

[[102 104   5]
 [100 100   3]
 [100   7 104]
 [  1   9 106]]


In [63]:
matrixC = np.random.randint(0, 10, size=(4, 3))
print(matrixC)
matrixC[(matrixC > 3) & (matrixC < 9)] += 100
matrixC

[[5 3 7]
 [3 4 9]
 [0 6 6]
 [4 5 6]]


array([[105,   3, 107],
       [  3, 104,   9],
       [  0, 106, 106],
       [104, 105, 106]])

In [66]:
filter = (matrixC > 3) & (matrixC < 9)
matrixC[filter] += 100
print(matrixC)

[[105   3 107]
 [  3 104   9]
 [  0 106 106]
 [104 105 106]]


In [68]:
matrixA1 = np.random.randint(0, 10, size=(2, 2))
matrixA2 = np.random.randint(0, 10, size=(2, 2))
print("matrixA1")
print(matrixA1)
print("matrixA2")
print(matrixA2)

matrixA1
[[6 0]
 [8 3]]
matrixA2
[[1 4]
 [4 5]]


In [71]:
print("Suma")
print(matrixA1 + matrixA2)
print("Resta")
print(matrixA1 - matrixA2)
print("Multiplicacion")
print(matrixA1 * matrixA2)
print("Division")
print(matrixA1 / matrixA2)


Suma
[[ 7  4]
 [12  8]]
Resta
[[ 5 -4]
 [ 4 -2]]
Multiplicacion
[[ 6  0]
 [32 15]]
Division
[[6.  0. ]
 [2.  0.6]]


In [74]:
print(matrixA1)
print("matrixA1")
print(np.sqrt(matrixA1))

[[6 0]
 [8 3]]
matrixA1
[[2.44948974 0.        ]
 [2.82842712 1.73205081]]


In [75]:
matrixA1=np.random.randint(0,10,size=(2,5))
print(matrixA1)

[[0 9 7 6 9]
 [4 6 2 8 4]]


In [77]:
print(np.mean(matrixA1))

5.5


In [79]:
print(matrixA1.mean(axis=1))

[6.2 4.8]


In [81]:
print(matrixA1.mean(axis=0))

[2.  7.5 4.5 7.  6.5]


In [83]:
print(np.median(matrixA1))

6.0


In [85]:
print(matrixA1.sum())

55


In [86]:
print(matrixA1.max())

9


In [88]:
print(matrixA1.std())

2.8372521918222215


In [89]:
print(matrixA1.var())

8.05


In [90]:
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [91]:
add_rows=np.array([[1,2,3]])
print(add_rows.shape)

(1, 3)


In [92]:
y = start + add_rows
print(y)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [94]:
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [95]:
col_rows=np.array([[1,2,3,4]])

In [103]:
print(col_rows)

[[1 2 3 4]]


In [106]:
print(start)
tmp=col_rows.T
y2=start+tmp
print(y2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [108]:
tmp1=np.array([[1,1], [2,2]])
tmp2=np.array([[3,3], [4,4]])
print(tmp1)
print(tmp2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [110]:
print(np.dot(tmp1, tmp2))

[[ 7  7]
 [14 14]]


In [112]:
print(tmp1.dot(tmp2))

[[ 7  7]
 [14 14]]


In [114]:
y1=np.random.randint(low=2,high=50,size=(2,2))
y2=np.random.randint(low=2,high=50,size=(2,2))
print(y1)
print(y2)

[[45 19]
 [12 10]]
[[11 37]
 [12 36]]


In [116]:
np.vstack((y1,y2))

array([[45, 19],
       [12, 10],
       [11, 37],
       [12, 36]])

In [117]:
np.hstack((y1,y2))

array([[45, 19, 11, 37],
       [12, 10, 12, 36]])