<a href="https://colab.research.google.com/github/thonyvel98/InteligenciaArtificial2024-2/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Library**

In [3]:
import numpy as np

In [5]:
print ( np.__version__ )

1.26.4


In [7]:
myArray=np.array([1,2,3,4,5])
print(myArray)

[1 2 3 4 5]


In [9]:
print(type(myArray))

<class 'numpy.ndarray'>


In [12]:
print(myArray.shape)
print(myArray[2])
myArray[2]=29
print(myArray[2])
print(myArray)

(5,)
29
29
[ 1  2 29  4  5]


In [14]:
myArray1=np.array([[1,2,3],[4,5,6]])
print(myArray1)
print(myArray1.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [17]:
myArray2=np.zeros((5,5))
print(myArray2)
print(myArray2.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)


In [22]:
myArray3=np.full((3,6),7)
print(myArray3)
myArray4=np.eye(5)
print(myArray4)
myArray5=np.ones((5,5))
print(myArray5)
print(myArray3.shape)

[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(3, 6)


In [26]:
myArray6=np.random.random((5,5))
print(myArray6)

[[0.91003894 0.74935487 0.26409957 0.88895042 0.97911427]
 [0.8927795  0.38751029 0.6257352  0.48130872 0.06032334]
 [0.42275371 0.47905218 0.83317842 0.04342948 0.25361036]
 [0.85307233 0.15992572 0.1412706  0.06021879 0.82365058]
 [0.56293695 0.74709116 0.96999458 0.04800417 0.10258756]]


In [33]:
myArray7=np.random.randint(100,size=(5,5))
print(myArray7)

[[27 63 62 40 10]
 [18  8 83 38 42]
 [17 76 11 39 15]
 [93 56 52 94 88]
 [91 15 17 58 90]]


In [32]:
newMatrix=myArray7[:2, :2]
print(newMatrix)

[[88 35]
 [68  9]]


In [37]:
myArray7[2,2]=1000000
print(myArray7)

[[     27      63      62      40      10]
 [     18       8      83      38      42]
 [     17      76 1000000      39      15]
 [     93      56      52     100      88]
 [     91      15      17      58      90]]


In [39]:
print(myArray7[2,:])

[     17      76 1000000      39      15]


In [47]:
print(myArray7[:,2].shape)

(5,)


In [51]:
newMatrix2=myArray7[1:4,1:4]
print(newMatrix2)

[[      8      83      38]
 [     76 1000000      39]
 [     56      52     100]]
